"""Discrete fixed-step TDP/eigen-train pulse encoding."""
from __future__ import annotations
from dataclasses import dataclass
import numpy as np

@dataclass(frozen=True)
class PulseSequence:
    """Polarity-aware square-wave samples generated by a fixed-step counter."""
    samples: np.ndarray
    step: float
    polarity: int
    @property
    def duration(self): return float(self.samples.size * self.step)
    @property
    def pulse_count(self): return int(np.abs(self.samples).sum())

def eigen_train(value: int, *, bits: int = 5, step: float = 1.0) -> PulseSequence:
    """For unsigned value, bit n contributes 2**n pulses with period 2**bits/2**n."""
    if type(value) is not int or type(bits) is not int or bits < 1 or value < 0 or value >= (1 << bits):
        raise ValueError("value must be an integer in the configured unsigned range")
    if not isinstance(step, (int, float)) or not np.isfinite(step) or step <= 0:
        raise ValueError("step must be a positive finite number")
    window = 1 << bits
    samples = np.zeros(window, dtype=np.int8)
    for bit in range(bits):
        if value & (1 << bit): samples[::window >> bit] += 1
    return PulseSequence(samples, float(step), 1)

def signed_eigen_train(value: int, *, bits: int = 5, step: float = 1.0) -> PulseSequence:
    """Generate a signed train; polarity selects positive or negative TDP."""
    if type(value) is not int or value < -(1 << (bits - 1)) or value > (1 << (bits - 1)) - 1:
        raise ValueError("value must fit the configured signed two's-complement range")
    polarity = 0 if value == 0 else (1 if value > 0 else -1)
    train = eigen_train(abs(value), bits=bits, step=step)
    return PulseSequence(train.samples * polarity, train.step, polarity)

def tdp_sequence_from_count(count: int, *, bits: int = 5, step: float = 1.0) -> PulseSequence:
    """Generate a nonnegative count waveform for a TDP counter."""
    return eigen_train(count, bits=bits, step=step)


